[
    {
        "creatorName": "Alex Morgan",
        "creatorEmail": "alex.m@example.com",
        "contestTitle": "Modern Minimalist Logo Design",
        "contestImage": "https://i.ibb.co.com/ym2pDKN7/milad-fakurian-CK8u2-I4-qw-unsplash.jpg",
        "contestDescription": "Create a clean, minimalist brand logo for an AI startup focused on sustainable tech. The design should reflect modern elegance and environmental consciousness.",
        "contestPrice": "15",
        "contestPrizeMoney": "300",
        "contestType": "Logo Design",
        "contestDeadline": "2026-08-15T23:59",
        "contestTaskInstructions": "Submit high-resolution SVG and PNG formats with vector source files. Transparent background is required.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 31,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-75810fE"
    },
    {
        "creatorName": "Sophia Chen",
        "creatorEmail": "sophia.chen@example.com",
        "contestTitle": "E-Commerce App UX/UI Redesign",
        "contestImage": "https://i.ibb.co.com/hq2HRMm/UI-UX-Design.png",
        "contestDescription": "Design a user-friendly mobile app interface for a fast-growing fashion marketplace. Focus on checkout optimization and mobile accessibility.",
        "contestPrice": "25",
        "contestPrizeMoney": "600",
        "contestType": "UI/UX Design",
        "contestDeadline": "2026-08-20T18:00",
        "contestTaskInstructions": "Provide Figma share link with organized components, auto-layout, and interactive prototype link.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 14,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-735810E"
    },
    {
        "creatorName": "David Miller",
        "creatorEmail": "david.m@example.com",
        "contestTitle": "Tech Innovators Conference Poster",
        "contestImage": "https://i.ibb.co.com/Vpz5FFvD/Graphic-Design.png",
        "contestDescription": "We need a futuristic poster for an upcoming global tech summit. Bold typography and vibrant color schemes are highly preferred.",
        "contestPrice": "10",
        "contestPrizeMoney": "200",
        "contestType": "Graphic Design",
        "contestDeadline": "2026-08-10T12:00",
        "contestTaskInstructions": "Print-ready PDF with CMYK color profile (300 DPI) along with editable PSD or AI file.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 81,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-745810E"
    },
    {
        "creatorName": "Emma Watson",
        "creatorEmail": "emma.w@example.com",
        "contestTitle": "SaaS Product Explainer Video Script",
        "contestImage": "https://i.ibb.co.com/tp5VzhTQ/Gemini-Generated-Image-lz3305lz3305lz33.png",
        "contestDescription": "Looking for an engaging 90-second explainer script for our HR automation software. Needs a witty, energetic, and professional tone.",
        "contestPrice": "12",
        "contestPrizeMoney": "250",
        "contestType": "Article Writing",
        "contestDeadline": "2026-08-12T15:30",
        "contestTaskInstructions": "Provide PDF/Docx format containing scene descriptions, screen directions, and voiceover text separately.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 61,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-7581110E"
    },
    {
        "creatorName": "Liam Johnson",
        "creatorEmail": "liam.j@example.com",
        "contestTitle": "Cyberpunk Game Character Art",
        "contestImage": "https://i.ibb.co.com/C3HstSNz/Digital-Art.jpg",
        "contestDescription": "Render a high-detail 2D character concept for an indie cyberpunk RPG game. The character should be a renegade hacker with glowing cyberware.",
        "contestPrice": "20",
        "contestPrizeMoney": "450",
        "contestType": "Digital Art",
        "contestDeadline": "2026-08-25T20:00",
        "contestTaskInstructions": "High-res PNG (4K resolution) plus layered PSD showing rough sketch to final line art and color steps.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 51,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-758010E"
    },
    {
        "creatorName": "Olivia Brown",
        "creatorEmail": "olivia.b@example.com",
        "contestTitle": "Eco-Friendly Coffee Packaging Design",
        "contestImage": "https://i.ibb.co.com/fznYv6z3/Packaging-Design.png",
        "contestDescription": "Design an elegant packaging bag for premium organic coffee beans. Earthy tones, clear typography, and recyclable vibe required.",
        "contestPrice": "18",
        "contestPrizeMoney": "350",
        "contestType": "Packaging Design",
        "contestDeadline": "2026-08-18T22:00",
        "contestTaskInstructions": "Dieline template print-ready vector file with mockups included in high-res JPG.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 31,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-785810E"
    },
    {
        "creatorName": "James Wilson",
        "creatorEmail": "james.w@example.com",
        "contestTitle": "Full-Stack Portfolio Website Template",
        "contestImage": "https://i.ibb.co.com/pBjMY4hD/software-developer-6521720-1280.jpg",
        "contestDescription": "Build a responsive React + Tailwind CSS portfolio template tailored for software developers with dark mode support.",
        "contestPrice": "30",
        "contestPrizeMoney": "800",
        "contestType": "Web Development",
        "contestDeadline": "2026-08-30T23:59",
        "contestTaskInstructions": "GitHub repository URL with clear README deployment instructions. Clean modular code is essential.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 61,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-758m10E"
    },
    {
        "creatorName": "Isabella Garcia",
        "creatorEmail": "isabella.g@example.com",
        "contestTitle": "Summer Fashion Photography Shoot",
        "contestImage": "https://i.ibb.co.com/QFGpy9XN/szabo-viktor-4-LDo-Re-Lne8-unsplash.jpg",
        "contestDescription": "Submit creative outdoor fashion portrait photography captured during golden hour. Looking for vibrant tones and artistic framing.",
        "contestPrice": "15",
        "contestPrizeMoney": "300",
        "contestType": "Photography",
        "contestDeadline": "2026-08-14T17:00",
        "contestTaskInstructions": "JPEG format (minimum 3000px on long edge) with EXIF data intact. No heavy watermark.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 41,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-7581jd0E"
    },
    {
        "creatorName": "Noah Martinez",
        "creatorEmail": "noah.m@example.com",
        "contestTitle": "Fintech Mobile App Promo Video (30s)",
        "contestImage": "https://i.ibb.co.com/5hkJ5Pq4/videoa.webp",
        "contestDescription": "Create a fast-paced 30-second motion graphics promo video highlighting instant money transfer features for a mobile banking app.",
        "contestPrice": "22",
        "contestPrizeMoney": "500",
        "contestType": "Video Editing",
        "contestDeadline": "2026-08-22T19:00",
        "contestTaskInstructions": "Submit MP4 file (1080x1920 portrait & 1920x1080 landscape). After Effects source file requested upon winning.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 91,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-7581ss0E"
    },
    {
        "creatorName": "Ava Taylor",
        "creatorEmail": "ava.t@example.com",
        "contestTitle": "Fantasy Novel Cover Design",
        "contestImage": "https://i.ibb.co.com/Vpz5FFvD/Graphic-Design.png",
        "contestDescription": "Book cover art for a mystery fantasy novel titled 'The Secret of Eldoria'. Should feature a glowing ancient key and magical forest backdrop.",
        "contestPrice": "15",
        "contestPrizeMoney": "350",
        "contestType": "Graphic Design",
        "contestDeadline": "2026-08-17T21:00",
        "contestTaskInstructions": "Front cover, spine, and back cover layout in print-ready PDF and high-res JPG.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 21,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-7581a0E"
    },
    {
        "creatorName": "Ethan Anderson",
        "creatorEmail": "ethan.a@example.com",
        "contestTitle": "Short Story: The Last City on Mars",
        "contestImage": "https://i.ibb.co.com/tp5VzhTQ/Gemini-Generated-Image-lz3305lz3305lz33.png",
        "contestDescription": "Write a compelling 2,000-word sci-fi story about human survival in a dome city on Mars during a global blackout.",
        "contestPrice": "10",
        "contestPrizeMoney": "200",
        "contestType": "Article Writing",
        "contestDeadline": "2026-08-11T23:00",
        "contestTaskInstructions": "PDF or DOCX document with standard 12pt Times New Roman font and double spacing.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 42,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-753810E"
    },
    {
        "creatorName": "Mia Thomas",
        "creatorEmail": "mia.t@example.com",
        "contestTitle": "Fitness Tracker App Dashboard UI",
        "contestImage": "https://i.ibb.co.com/hq2HRMm/UI-UX-Design.png",
        "contestDescription": "Design an interactive fitness analytics dashboard showing daily step counts, calorie burn, heart rate charts, and workout history.",
        "contestPrice": "20",
        "contestPrizeMoney": "400",
        "contestType": "UI/UX Design",
        "contestDeadline": "2026-08-19T16:00",
        "contestTaskInstructions": "Figma design system, component variants, and responsive desktop/mobile view layouts.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 33,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-7581b0E"
    },
    {
        "creatorName": "Lucas White",
        "creatorEmail": "lucas.w@example.com",
        "contestTitle": "3D Mascot Design for Gaming Brand",
        "contestImage": "https://i.ibb.co.com/C3HstSNz/Digital-Art.jpg",
        "contestDescription": "Craft a friendly yet fierce 3D robot dragon mascot for an esports platform. Should look great on T-shirts and stickers.",
        "contestPrice": "25",
        "contestPrizeMoney": "550",
        "contestType": "Digital Art",
        "contestDeadline": "2026-08-26T18:00",
        "contestTaskInstructions": "FBX/OBJ 3D file along with rendered high-res PNG images from front, side, and isometric angles.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 62,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-758c10E"
    },
    {
        "creatorName": "Charlotte Harris",
        "creatorEmail": "charlotte.h@example.com",
        "contestTitle": "Organic Skincare Brand Identity",
        "contestImage": "https://i.ibb.co.com/ym2pDKN7/milad-fakurian-CK8u2-I4-qw-unsplash.jpg",
        "contestDescription": "Comprehensive branding guide including color palette, typography selection, logo usage guidelines, and social media banner templates.",
        "contestPrice": "20",
        "contestPrizeMoney": "450",
        "contestType": "Logo Design",
        "contestDeadline": "2026-08-21T20:00",
        "contestTaskInstructions": "Brand guidelines book in PDF format along with editable Adobe Illustrator master files.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 50,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-758l10E"
    },
    {
        "creatorName": "Benjamin Martin",
        "creatorEmail": "benjamin.m@example.com",
        "contestTitle": "AI Chatbot Web Interface",
        "contestImage": "https://i.ibb.co.com/pBjMY4hD/software-developer-6521720-1280.jpg",
        "contestDescription": "Build a clean web UI using Tailwind CSS for an AI assistant app featuring chat history sidebars, prompt suggestions, and code highlighting.",
        "contestPrice": "25",
        "contestPrizeMoney": "500",
        "contestType": "Web Development",
        "contestDeadline": "2026-08-24T22:30",
        "contestTaskInstructions": "Live Netlify/Vercel link along with GitHub code repository access.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 33,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-7581h0E"
    },
    {
        "creatorName": "Amelia Clark",
        "creatorEmail": "amelia.c@example.com",
        "contestTitle": "Minimalist Ceramic Mug Packaging",
        "contestImage": "https://i.ibb.co.com/fznYv6z3/Packaging-Design.png",
        "contestDescription": "Design a sturdy cardboard box packaging for handmade ceramic coffee mugs emphasizing eco-friendliness and artisan craft.",
        "contestPrice": "12",
        "contestPrizeMoney": "250",
        "contestType": "Packaging Design",
        "contestDeadline": "2026-08-13T14:00",
        "contestTaskInstructions": "Dieline blueprint with CMYK color settings and realistic 3D renderings.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 31,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-202607625-75810E"
    },
    {
        "creatorName": "Henry Lewis",
        "creatorEmail": "henry.l@example.com",
        "contestTitle": "Travel Vlogger Intro Animation",
        "contestImage": "https://i.ibb.co.com/5hkJ5Pq4/videoa.webp",
        "contestDescription": "Create a 5-second energetic title intro animation for a popular YouTube travel channel. Needs sound effects included.",
        "contestPrice": "15",
        "contestPrizeMoney": "300",
        "contestType": "Video Editing",
        "contestDeadline": "2026-08-16T19:00",
        "contestTaskInstructions": "1080p 60fps MP4 video file and After Effects project file.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 10,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-754810E"
    },
    {
        "creatorName": "Harper Walker",
        "creatorEmail": "harper.w@example.com",
        "contestTitle": "Street Art Architecture Photography",
        "contestImage": "https://i.ibb.co.com/QFGpy9XN/szabo-viktor-4-LDo-Re-Lne8-unsplash.jpg",
        "contestDescription": "Capture vibrant graffiti and urban mural street art seamlessly integrated with modern city architectural elements.",
        "contestPrice": "10",
        "contestPrizeMoney": "200",
        "contestType": "Photography",
        "contestDeadline": "2026-08-09T18:00",
        "contestTaskInstructions": "High-resolution RAW + JPEG files without aggressive post-processing filters.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 21,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-7581v0E"
    },
    {
        "creatorName": "Sebastian Hall",
        "creatorEmail": "sebastian.h@example.com",
        "contestTitle": "Tech Review Blog Post Series",
        "contestImage": "https://i.ibb.co.com/tp5VzhTQ/Gemini-Generated-Image-lz3305lz3305lz33.png",
        "contestDescription": "Write an in-depth 1500-word SEO-optimized blog review comparing top wireless noise-canceling headphones of the year.",
        "contestPrice": "12",
        "contestPrizeMoney": "250",
        "contestType": "Article Writing",
        "contestDeadline": "2026-08-16T12:00",
        "contestTaskInstructions": "Provide Markdown format file with subheadings, target keywords, and image placement suggestions.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 70,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-758r10E"
    },
    {
        "creatorName": "Ella Allen",
        "creatorEmail": "ella.a@example.com",
        "contestTitle": "NFT Pixel Art Collection Starter",
        "contestImage": "https://i.ibb.co.com/C3HstSNz/Digital-Art.jpg",
        "contestDescription": "Design 5 unique 64x64 pixel art characters with distinct traits (hats, glasses, backgrounds) for an upcoming NFT drop.",
        "contestPrice": "20",
        "contestPrizeMoney": "400",
        "contestType": "Digital Art",
        "contestDeadline": "2026-08-23T20:00",
        "contestTaskInstructions": "Exported transparent PNGs scaled up to 1024x1024 alongside original PSD/Aseprite source files.",
        "contestCreationFee": 10,
        "createdAt": "2026-07-25T08:31:08.644+00:00",
        "participantsCount": 81,
        "paymentStatus": "paid",
        "submitStatus": "submit-done",
        "trackingId": "PRCL-20260725-75810eE"
    }
]